version: "3.8"

services:
  leptos-builder-musl:
    build:
      context: .
      dockerfile: Dockerfile.builder-musl
    image: leptos-builder-musl
    volumes:
      - .:/work
    command: /bin/bash

  blog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_DB=${POSTGRES_DB}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - LEPTOS_OUTPUT_NAME=blog
      - LEPTOS_SITE_ROOT=./site
      - LEPTOS_SITE_PKG_DIR=./pkg
      - LEPTOS_SITE_ADDR=0.0.0.0:3000
      - LEPTOS_RELOAD_PORT=3001
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - leptos-builder-musl
