version: "3.8"

services:
    blog:
        build:
            context: .
            args:
                - POSTGRES_USER=${BUILD_POSTGRES_USER}
                - POSTGRES_PASSWORD=${BUILD_POSTGRES_PASSWORD}
                - POSTGRES_HOST=${BUILD_POSTGRES_HOST}
                - POSTGRES_PORT=${BUILD_POSTGRES_PORT}
                - POSTGRES_DB=${BUILD_POSTGRES_DB}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "3000:3000"
