version: "3.8"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_DB=${POSTGRES_DB}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 5s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_HOST_FILE=/run/secrets/postgres_host
      - POSTGRES_PORT_FILE=/run/secrets/postgres_port
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - LEPTOS_OUTPUT_NAME=blog
      - LEPTOS_SITE_ROOT=./site
      - LEPTOS_SITE_PKG_DIR=./pkg
      - LEPTOS_SITE_ADDR=0.0.0.0:3000
    ports:
      - "3000:3000"
    volumes:
      - blog-data:/app/data
    secrets:
      - postgres_user
      - postgres_password
      - postgres_host
      - postgres_port
      - postgres_db

volumes:
  blog-data:
    driver: local

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_host:
    external: true
  postgres_port:
    external: true
  postgres_db:
    external: true
